services:
  - type: web
    name: dogbreedpwa
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    rootDir: dogbreedpwa  # ← 중요: dogbreedpwa가 app.py 있는 폴더
